name: SGI Framework Angular

on:
  workflow_dispatch:
  push:
    paths:
      - 'projects/datetime-picker/**'
      - '.github/workflows/datetime-picker.yml'
    branches:
      - sgi

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js 14 for build
      uses: actions/setup-node@v4
      with:
        node-version: '14.x'

    - name: Install dependencias
      run: npm install

    - name: Build
      run: |
        cd projects/datetime-picker
        export VERSION=$(cat package.json | grep version | head -1 | awk -F= "{ print $2 }" | sed -E 's/"version":|"|,//g' | tr -d '[[:space:]]')

        if [[ "$VERSION" == *SNAPSHOT* ]]; then
          npm version --commit-hooks=false --git-tag-version=false $VERSION.$(date +%Y%m%d%H%M%S)
        fi

        cd ../..
        npm run build:datetime-picker

    - name: Use Node.js 24 for publish
      uses: actions/setup-node@v4
      with:
        node-version: '24.x'
        registry-url: 'https://registry.npmjs.org'

    - name: Publish
      run: npm publish --provenance --access public --tag sgi dist/@herculesproject/datetime-picker
